import {
  IncomeTaxCalculatorUSStateKey,
  IncomeTaxCalculatorUSState,
} from './incomeTaxCalculatorTypes';

export const INCOME_TAX_CALCULATOR_US_STATES_KEYS = Object.keys(
  IncomeTaxCalculatorUSStateKey,
) as (keyof typeof IncomeTaxCalculatorUSStateKey)[];

export const INCOME_TAX_CALCULATOR_US_STATE_KEY_TO_NAME: Record<
  IncomeTaxCalculatorUSState,
  string
> = {
  [IncomeTaxCalculatorUSStateKey.AL]: 'Alabama',
  [IncomeTaxCalculatorUSStateKey.AK]: 'Alaska',
  [IncomeTaxCalculatorUSStateKey.AZ]: 'Arizona',
  [IncomeTaxCalculatorUSStateKey.AR]: 'Arkansas',
  [IncomeTaxCalculatorUSStateKey.CA]: 'California',
  [IncomeTaxCalculatorUSStateKey.CO]: 'Colorado',
  [IncomeTaxCalculatorUSStateKey.CT]: 'Connecticut',
  [IncomeTaxCalculatorUSStateKey.DE]: 'Delaware',
  [IncomeTaxCalculatorUSStateKey.FL]: 'Florida',
  [IncomeTaxCalculatorUSStateKey.GA]: 'Georgia',
  [IncomeTaxCalculatorUSStateKey.HI]: 'Hawaii',
  [IncomeTaxCalculatorUSStateKey.ID]: 'Idaho',
  [IncomeTaxCalculatorUSStateKey.IL]: 'Illinois',
  [IncomeTaxCalculatorUSStateKey.IN]: 'Indiana',
  [IncomeTaxCalculatorUSStateKey.IA]: 'Iowa',
  [IncomeTaxCalculatorUSStateKey.KS]: 'Kansas',
  [IncomeTaxCalculatorUSStateKey.KY]: 'Kentucky',
  [IncomeTaxCalculatorUSStateKey.LA]: 'Louisiana',
  [IncomeTaxCalculatorUSStateKey.ME]: 'Maine',
  [IncomeTaxCalculatorUSStateKey.MD]: 'Maryland',
  [IncomeTaxCalculatorUSStateKey.MA]: 'Massachusetts',
  [IncomeTaxCalculatorUSStateKey.MI]: 'Michigan',
  [IncomeTaxCalculatorUSStateKey.MN]: 'Minnesota',
  [IncomeTaxCalculatorUSStateKey.MS]: 'Mississippi',
  [IncomeTaxCalculatorUSStateKey.MO]: 'Missouri',
  [IncomeTaxCalculatorUSStateKey.MT]: 'Montana',
  [IncomeTaxCalculatorUSStateKey.NE]: 'Nebraska',
  [IncomeTaxCalculatorUSStateKey.NV]: 'Nevada',
  [IncomeTaxCalculatorUSStateKey.NH]: 'New Hampshire',
  [IncomeTaxCalculatorUSStateKey.NJ]: 'New Jersey',
  [IncomeTaxCalculatorUSStateKey.NM]: 'New Mexico',
  [IncomeTaxCalculatorUSStateKey.NY]: 'New York',
  [IncomeTaxCalculatorUSStateKey.NC]: 'North Carolina',
  [IncomeTaxCalculatorUSStateKey.ND]: 'North Dakota',
  [IncomeTaxCalculatorUSStateKey.OH]: 'Ohio',
  [IncomeTaxCalculatorUSStateKey.OK]: 'Oklahoma',
  [IncomeTaxCalculatorUSStateKey.OR]: 'Oregon',
  [IncomeTaxCalculatorUSStateKey.PA]: 'Pennsylvania',
  [IncomeTaxCalculatorUSStateKey.RI]: 'Rhode Island',
  [IncomeTaxCalculatorUSStateKey.SC]: 'South Carolina',
  [IncomeTaxCalculatorUSStateKey.SD]: 'South Dakota',
  [IncomeTaxCalculatorUSStateKey.TN]: 'Tennessee',
  [IncomeTaxCalculatorUSStateKey.TX]: 'Texas',
  [IncomeTaxCalculatorUSStateKey.UT]: 'Utah',
  [IncomeTaxCalculatorUSStateKey.VT]: 'Vermont',
  [IncomeTaxCalculatorUSStateKey.VA]: 'Virginia',
  [IncomeTaxCalculatorUSStateKey.WA]: 'Washington',
  [IncomeTaxCalculatorUSStateKey.WV]: 'West Virginia',
  [IncomeTaxCalculatorUSStateKey.WI]: 'Wisconsin',
  [IncomeTaxCalculatorUSStateKey.WY]: 'Wyoming',
  [IncomeTaxCalculatorUSStateKey.DC]: 'District of Columbia',
};
